// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FitnessArena_API.Models
{
    [Table("bundle")]
    public partial class bundle
    {
        public bundle()
        {
            traineeBundles = new HashSet<traineeBundle>();
        }

        [Key]
        public int bundleId { get; set; }
        [Required]
        [StringLength(10)]
        [Unicode(false)]
        public string name { get; set; }
        public int fees { get; set; }
        public int coachId { get; set; }
        public int durationDays { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string description { get; set; }

        [ForeignKey("coachId")]
        [InverseProperty("bundles")]
        public virtual user coach { get; set; }
        [InverseProperty("bundle")]

        public virtual ICollection<traineeBundle> traineeBundles { get; set; }
    }
}