// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FitnessArena_API.Models
{
    [Table("commentLike")]
    public partial class commentLike
    {
        public int? userId { get; set; }
        public int? commentId { get; set; }
        [Key]
        public int commentlikeId { get; set; }

        [ForeignKey("commentId")]
        [InverseProperty("commentLikes")]
        public virtual postsComment comment { get; set; }
        [ForeignKey("userId")]
        [InverseProperty("commentLikes")]
        public virtual user user { get; set; }
    }
}