// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FitnessArena_API.Models
{
    public partial class Payment
    {
        [Key]
        public int paymentId { get; set; }
        [Column(TypeName = "date")]
        public DateTime? paymentDate { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string method { get; set; }
        public int amount { get; set; }
        public int coachId { get; set; }
        public int traineeId { get; set; }

        [ForeignKey("coachId")]
        [InverseProperty("Paymentcoaches")]
        public virtual user coach { get; set; }
        [ForeignKey("traineeId")]
        [InverseProperty("Paymenttrainees")]
        public virtual user trainee { get; set; }
    }
}