// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace FitnessArena_API.Models
{
    [Table("postsShare")]
    public partial class postsShare
    {
        public int? postId { get; set; }
        public int? userId { get; set; }
        [JsonIgnore]
        [Key]
        public int shareId { get; set; }

        [JsonIgnore]
        [ForeignKey("postId")]
        [InverseProperty("postsShares")]
        public virtual post post { get; set; }
        [JsonIgnore]
        [ForeignKey("userId")]
        [InverseProperty("postsShares")]
        public virtual user user { get; set; }
    }
}