// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace FitnessArena_API.Models
{
    [Table("programWorkout")]
    public partial class programWorkout
    {
        public int? workoutId { get; set; }
        public int? programId { get; set; }
        [Key]
        public int progWork { get; set; }

        [JsonIgnore]
        [ForeignKey("programId")]
        [InverseProperty("programWorkouts")]
        public virtual program program { get; set; }
        [ForeignKey("workoutId")]
        [InverseProperty("programWorkouts")]
        [JsonIgnore]
        public virtual workout workout { get; set; }
    }
}