// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FitnessArena_API.Models
{
    public partial class workoutMedium
    {
        [Key]
        public int workoutId { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string videoUrl { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string videoName { get; set; }

        [ForeignKey("workoutId")]
        [InverseProperty("workoutMedium")]
        public virtual workout workout { get; set; }
    }
}